#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : diffstat
Version  : 1.61
Release  : 3
URL      : ftp://invisible-island.net/diffstat/diffstat-1.61.tgz
Source0  : ftp://invisible-island.net/diffstat/diffstat-1.61.tgz
Summary  : diffstat - make histogram from diff-output
Group    : Development/Tools
License  : MIT
Requires: diffstat-bin
Requires: diffstat-doc
BuildRequires : groff

%description
Diffstat is is useful for reviewing large, complex patch files.  It reads from
one or more input files which contain output from diff, producing a histogram
of the total lines changed for each file referenced.

%package bin
Summary: bin components for the diffstat package.
Group: Binaries

%description bin
bin components for the diffstat package.


%package doc
Summary: doc components for the diffstat package.
Group: Documentation

%description doc
doc components for the diffstat package.


%prep
%setup -q -n diffstat-1.61

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/diffstat

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
