#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x702353E0F7E48EDB (dickey@invisible-island.net)
#
Name     : diffstat
Version  : 1.64
Release  : 12
URL      : https://invisible-mirror.net/archives/diffstat/diffstat-1.64.tgz
Source0  : https://invisible-mirror.net/archives/diffstat/diffstat-1.64.tgz
Source1  : https://invisible-mirror.net/archives/diffstat/diffstat-1.64.tgz.asc
Summary  : diffstat - make histogram from diff-output
Group    : Development/Tools
License  : MIT
Requires: diffstat-bin = %{version}-%{release}
Requires: diffstat-man = %{version}-%{release}
BuildRequires : cppcheck
BuildRequires : ctags
BuildRequires : groff

%description
Diffstat is is useful for reviewing large, complex patch files.  It reads from
one or more input files which contain output from diff, producing a histogram
of the total lines changed for each file referenced.

%package bin
Summary: bin components for the diffstat package.
Group: Binaries

%description bin
bin components for the diffstat package.


%package man
Summary: man components for the diffstat package.
Group: Default

%description man
man components for the diffstat package.


%prep
%setup -q -n diffstat-1.64
cd %{_builddir}/diffstat-1.64

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1610576488
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1610576488
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/diffstat

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/diffstat.1
